
language: bash
services: docker

install:
  - git clone https://github.com/dggr/Ghost-sr.git

before_script:
  - env | sort
  - image='ghost'

script:
  - docker build -t "$image" .
  - ~/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
